version: "3.2.22"
services:
  site:
    container_name: docsy
    command: jekyll serve --watch --drafts
    image: jekyll/jekyll:4.0
    volumes:
      - "./:/srv/jekyll"
      - "./vendor/bundle:/usr/local/bundle"
      # remove "./vendor/bundle:/usr/local/bundle" volume when deploying in production
    ports:
      - "4000:4000"
